{
 "title": "MicroServices Platform Overview",
 "tags": [
  "microservices",
  "overview",
  "kafka",
  "aggregated"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "environment",
    "query": "label_values(jvm_classes_loaded_classes, env)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{env=\"$env\"}[1m]))",
     "legendFormat": "http request rate"
    }
   ]
  },
  {
   "title": "Kafka Consumption Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_records_consumed_total_records_total{env=\"$env\"}[1m]))",
     "legendFormat": "kafka consumption rate"
    }
   ]
  },
  { "title": "Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "samplemicrosvc-1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{appName=\"samplemicrosvc\", env=\"$env\", instanceId=\"1\"}",
     "legendFormat": "{{appName}}"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=~\"kafka.*\"}",
     "legendFormat": "{{appName}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Errors (since last restart)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(component_invocation_exception_counter_total{env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Failed HTTP Requests",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "sum by (uri) (http_server_requests_seconds_count{env=\"$env\", status!~\"20.\"})"
    }
   ]
  },
  {
   "title": "Failed Service Requests",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "sum by (componentClass) (component_invocation_exception_counter_total{env=\"$env\", status!~\"SUCCESS\"})"
    }
   ]
  },
  {
   "title": "Service Exceptions",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "component_invocation_exception_counter_total{outcome!=\"SUCCESS\", env=\"$env\", componentType!~\"dao\"}",
     "legendFormat": "{{componentType}}"
    }
   ]
  }
 ]
}